# INSTRUCTIONS
# Replace <email> and <password> with your LinkedIn login credentials

email: alessandro.tedeschitoschi@outlook.com
password: LinkeBotpassword

# INSTRUCTIONS
# Replace <PAGETOSEARCH> with the Linked handle to search
# Example 

pages: # Do not change this key
  - "<PAGETOSEARCH>"
  - "<PAGETOSEARCH>"
